[2024-05-14T04:46:32.475+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-05-14T04:46:32.524+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dag_with_postgres_to_file_3.postgres_to_file scheduled__2024-05-13T00:00:00+00:00 [queued]>
[2024-05-14T04:46:32.535+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dag_with_postgres_to_file_3.postgres_to_file scheduled__2024-05-13T00:00:00+00:00 [queued]>
[2024-05-14T04:46:32.536+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 6
[2024-05-14T04:46:32.564+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): postgres_to_file> on 2024-05-13 00:00:00+00:00
[2024-05-14T04:46:32.581+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=192) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-05-14T04:46:32.580+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'dag_with_postgres_to_file_3', 'postgres_to_file', 'scheduled__2024-05-13T00:00:00+00:00', '--job-id', '187', '--raw', '--subdir', 'DAGS_FOLDER/postgres_to_csv.py', '--cfg-path', '/tmp/tmpmb2rfqo3']
[2024-05-14T04:46:32.582+0000] {standard_task_runner.py:91} INFO - Job 187: Subtask postgres_to_file
[2024-05-14T04:46:32.582+0000] {standard_task_runner.py:63} INFO - Started process 201 to run task
[2024-05-14T04:46:32.650+0000] {task_command.py:426} INFO - Running <TaskInstance: dag_with_postgres_to_file_3.postgres_to_file scheduled__2024-05-13T00:00:00+00:00 [running]> on host dab92a57e2e4
[2024-05-14T04:46:32.813+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='myself' AIRFLOW_CTX_DAG_ID='dag_with_postgres_to_file_3' AIRFLOW_CTX_TASK_ID='postgres_to_file' AIRFLOW_CTX_EXECUTION_DATE='2024-05-13T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-05-13T00:00:00+00:00'
[2024-05-14T04:46:32.813+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-05-14T04:46:32.853+0000] {base.py:84} INFO - Using connection ID 'postgres_localhost' for task execution.
[2024-05-14T04:46:32.867+0000] {postgres_to_csv.py:27} INFO - Saved orders data in text file
[2024-05-14T04:46:32.868+0000] {python.py:237} INFO - Done. Returned value was: None
[2024-05-14T04:46:32.869+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-05-14T04:46:32.882+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=dag_with_postgres_to_file_3, task_id=postgres_to_file, run_id=scheduled__2024-05-13T00:00:00+00:00, execution_date=20240513T000000, start_date=20240514T044632, end_date=20240514T044632
[2024-05-14T04:46:32.929+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-05-14T04:46:32.962+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-05-14T04:46:32.967+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
