[2024-05-09T10:28:46.963+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-05-09T10:28:47.001+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dag_with_postgres_to_file_2.postgres_to_file scheduled__2024-05-08T00:00:00+00:00 [queued]>
[2024-05-09T10:28:47.012+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dag_with_postgres_to_file_2.postgres_to_file scheduled__2024-05-08T00:00:00+00:00 [queued]>
[2024-05-09T10:28:47.012+0000] {taskinstance.py:2306} INFO - Starting attempt 2 of 7
[2024-05-09T10:28:47.033+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): postgres_to_file> on 2024-05-08 00:00:00+00:00
[2024-05-09T10:28:47.041+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=12763) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-05-09T10:28:47.043+0000] {standard_task_runner.py:63} INFO - Started process 12764 to run task
[2024-05-09T10:28:47.041+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'dag_with_postgres_to_file_2', 'postgres_to_file', 'scheduled__2024-05-08T00:00:00+00:00', '--job-id', '128', '--raw', '--subdir', 'DAGS_FOLDER/postgres_to_csv.py', '--cfg-path', '/tmp/tmpgtvmcjqy']
[2024-05-09T10:28:47.043+0000] {standard_task_runner.py:91} INFO - Job 128: Subtask postgres_to_file
[2024-05-09T10:28:47.094+0000] {task_command.py:426} INFO - Running <TaskInstance: dag_with_postgres_to_file_2.postgres_to_file scheduled__2024-05-08T00:00:00+00:00 [running]> on host dab92a57e2e4
[2024-05-09T10:28:47.187+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='myself' AIRFLOW_CTX_DAG_ID='dag_with_postgres_to_file_2' AIRFLOW_CTX_TASK_ID='postgres_to_file' AIRFLOW_CTX_EXECUTION_DATE='2024-05-08T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-05-08T00:00:00+00:00'
[2024-05-09T10:28:47.188+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-05-09T10:28:47.215+0000] {base.py:84} INFO - Using connection ID 'postgres_localhost' for task execution.
[2024-05-09T10:28:47.223+0000] {postgres_to_csv.py:29} INFO - Saved orders data in text file
[2024-05-09T10:28:47.223+0000] {python.py:237} INFO - Done. Returned value was: None
[2024-05-09T10:28:47.224+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-05-09T10:28:47.234+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=dag_with_postgres_to_file_2, task_id=postgres_to_file, run_id=scheduled__2024-05-08T00:00:00+00:00, execution_date=20240508T000000, start_date=20240509T102847, end_date=20240509T102847
[2024-05-09T10:28:47.256+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-05-09T10:28:47.278+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-05-09T10:28:47.279+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
