[2024-05-09T10:24:58.554+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-05-09T10:24:58.626+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dag_with_postgres_to_file_1.postgres_to_file scheduled__2022-05-13T00:00:00+00:00 [queued]>
[2024-05-09T10:24:58.643+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dag_with_postgres_to_file_1.postgres_to_file scheduled__2022-05-13T00:00:00+00:00 [queued]>
[2024-05-09T10:24:58.644+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 6
[2024-05-09T10:24:58.787+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): postgres_to_file> on 2022-05-13 00:00:00+00:00
[2024-05-09T10:24:58.800+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=12460) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-05-09T10:24:58.802+0000] {standard_task_runner.py:63} INFO - Started process 12463 to run task
[2024-05-09T10:24:58.801+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'dag_with_postgres_to_file_1', 'postgres_to_file', 'scheduled__2022-05-13T00:00:00+00:00', '--job-id', '108', '--raw', '--subdir', 'DAGS_FOLDER/postgres_to_csv.py', '--cfg-path', '/tmp/tmpvr1wgbzs']
[2024-05-09T10:24:58.804+0000] {standard_task_runner.py:91} INFO - Job 108: Subtask postgres_to_file
[2024-05-09T10:24:58.892+0000] {task_command.py:426} INFO - Running <TaskInstance: dag_with_postgres_to_file_1.postgres_to_file scheduled__2022-05-13T00:00:00+00:00 [running]> on host dab92a57e2e4
[2024-05-09T10:24:59.046+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='myself' AIRFLOW_CTX_DAG_ID='dag_with_postgres_to_file_1' AIRFLOW_CTX_TASK_ID='postgres_to_file' AIRFLOW_CTX_EXECUTION_DATE='2022-05-13T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2022-05-13T00:00:00+00:00'
[2024-05-09T10:24:59.047+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-05-09T10:24:59.091+0000] {base.py:84} INFO - Using connection ID 'postgres_localhost' for task execution.
[2024-05-09T10:24:59.098+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-05-09T10:24:59.099+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/postgres_to_csv.py", line 22, in postgres_to_file
    cursor.execute("select * from orders where date >= 20220501")
psycopg2.errors.UndefinedFunction: operator does not exist: date >= integer
LINE 1: select * from orders where date >= 20220501
                                        ^
HINT:  No operator matches the given name and argument types. You might need to add explicit type casts.

[2024-05-09T10:24:59.114+0000] {taskinstance.py:1206} INFO - Marking task as UP_FOR_RETRY. dag_id=dag_with_postgres_to_file_1, task_id=postgres_to_file, run_id=scheduled__2022-05-13T00:00:00+00:00, execution_date=20220513T000000, start_date=20240509T102458, end_date=20240509T102459
[2024-05-09T10:24:59.135+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 108 for task postgres_to_file (operator does not exist: date >= integer
LINE 1: select * from orders where date >= 20220501
                                        ^
HINT:  No operator matches the given name and argument types. You might need to add explicit type casts.
; 12463)
[2024-05-09T10:24:59.181+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-05-09T10:24:59.206+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-05-09T10:24:59.209+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
