[2024-05-09T09:38:57.042+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-05-09T09:38:57.077+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dag_with_postgres_hooks_v02.create_orders_table scheduled__2024-05-08T00:00:00+00:00 [queued]>
[2024-05-09T09:38:57.087+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dag_with_postgres_hooks_v02.create_orders_table scheduled__2024-05-08T00:00:00+00:00 [queued]>
[2024-05-09T09:38:57.087+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 6
[2024-05-09T09:38:57.108+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): create_orders_table> on 2024-05-08 00:00:00+00:00
[2024-05-09T09:38:57.114+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=9803) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-05-09T09:38:57.115+0000] {standard_task_runner.py:63} INFO - Started process 9804 to run task
[2024-05-09T09:38:57.115+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'dag_with_postgres_hooks_v02', 'create_orders_table', 'scheduled__2024-05-08T00:00:00+00:00', '--job-id', '78', '--raw', '--subdir', 'DAGS_FOLDER/postgres_hooks.py', '--cfg-path', '/tmp/tmp3d70uzlp']
[2024-05-09T09:38:57.117+0000] {standard_task_runner.py:91} INFO - Job 78: Subtask create_orders_table
[2024-05-09T09:38:57.166+0000] {task_command.py:426} INFO - Running <TaskInstance: dag_with_postgres_hooks_v02.create_orders_table scheduled__2024-05-08T00:00:00+00:00 [running]> on host dab92a57e2e4
[2024-05-09T09:38:57.246+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='myself' AIRFLOW_CTX_DAG_ID='dag_with_postgres_hooks_v02' AIRFLOW_CTX_TASK_ID='create_orders_table' AIRFLOW_CTX_EXECUTION_DATE='2024-05-08T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-05-08T00:00:00+00:00'
[2024-05-09T09:38:57.247+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-05-09T09:38:57.269+0000] {base.py:84} INFO - Using connection ID 'postgres_localhost' for task execution.
[2024-05-09T09:38:57.270+0000] {logging_mixin.py:188} INFO - Error: connection to server at "localhost" (127.0.0.1), port 5432 failed: Connection refused
	Is the server running on that host and accepting TCP/IP connections?
connection to server at "localhost" (::1), port 5432 failed: Cannot assign requested address
	Is the server running on that host and accepting TCP/IP connections?
[2024-05-09T09:38:57.270+0000] {python.py:237} INFO - Done. Returned value was: None
[2024-05-09T09:38:57.271+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-05-09T09:38:57.278+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=dag_with_postgres_hooks_v02, task_id=create_orders_table, run_id=scheduled__2024-05-08T00:00:00+00:00, execution_date=20240508T000000, start_date=20240509T093857, end_date=20240509T093857
[2024-05-09T09:38:57.329+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-05-09T09:38:57.370+0000] {taskinstance.py:3498} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2024-05-09T09:38:57.375+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
